//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mbia.price.pom_upload_reminders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Price_Entities : DbContext
    {
        public Price_Entities()
            : base("name=Price_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblPriceRequest> tblPriceRequests { get; set; }
        public virtual DbSet<tblPCRItem> tblPCRItems { get; set; }
    
        public virtual ObjectResult<Get_POM_Pending_PCRs_Result> Get_POM_Pending_PCRs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_POM_Pending_PCRs_Result>("Get_POM_Pending_PCRs");
        }
    
        public virtual ObjectResult<Get_Items_By_PCRId_Result> Get_Items_By_PCRId(Nullable<int> pcrId)
        {
            var pcrIdParameter = pcrId.HasValue ?
                new ObjectParameter("PcrId", pcrId) :
                new ObjectParameter("PcrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Items_By_PCRId_Result>("Get_Items_By_PCRId", pcrIdParameter);
        }
    }
}
