//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mbia.price.pom_upload_reminders
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPCRItem
    {
        public int PCR_Id { get; set; }
        public string Item_Nbr { get; set; }
        public string Item_Desc { get; set; }
        public Nullable<decimal> New_Retail { get; set; }
        public Nullable<int> Reason_Code { get; set; }
        public string New_Ticket_Type { get; set; }
        public Nullable<decimal> Osceola_New_Retail { get; set; }
        public Nullable<decimal> Orange_New_Retail { get; set; }
        public Nullable<decimal> DCL_New_Retail { get; set; }
        public Nullable<decimal> DLR_New_Retail { get; set; }
        public Nullable<decimal> Aulani_New_Retail { get; set; }
        public Nullable<decimal> Old_Retail { get; set; }
    }
}
