//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mbia.price.pom_upload_reminders
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceRequest
    {
        public string PCR_Nbr { get; set; }
        public string PCR_Desc { get; set; }
        public int PCR_Id { get; set; }
        public string PCR_Status { get; set; }
        public string Pricing_Analyst { get; set; }
        public string Requested_By { get; set; }
        public string Dept_Nbr_Nm { get; set; }
        public string Planner_Nm { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Requested_Date { get; set; }
        public string Price_Zone { get; set; }
        public string Change_Type { get; set; }
        public string Specific_Location { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public string Effective_Date_Added_By { get; set; }
        public Nullable<System.DateTime> Effective_Date_Added_On { get; set; }
        public Nullable<System.DateTime> Last_Modified_On { get; set; }
        public string Pricer_Confirmed_By { get; set; }
        public Nullable<System.DateTime> Pricer_Confirmed_On { get; set; }
        public string Sign_Request_Sent_By { get; set; }
        public Nullable<System.DateTime> Sign_Request_Sent_On { get; set; }
        public string Sign_Request_Confirmed_By { get; set; }
        public Nullable<System.DateTime> Sign_Request_Confirmed_On { get; set; }
        public string MPI_Confirmed_By { get; set; }
        public Nullable<System.DateTime> MPI_Confirmed_On { get; set; }
        public string POM_Request_Sent_By { get; set; }
        public Nullable<System.DateTime> POM_Request_Sent_On { get; set; }
        public string Sourcing_Request_Sent_By { get; set; }
        public Nullable<System.DateTime> Sourcing_Request_Sent_On { get; set; }
        public string Supplier_Notification_Sent_By { get; set; }
        public Nullable<System.DateTime> Supplier_Notification_Sent_On { get; set; }
        public string Supplier_Confirmed_By { get; set; }
        public Nullable<System.DateTime> Supplier_Confirmed_On { get; set; }
        public string PO_Comments_Sent_By { get; set; }
        public Nullable<System.DateTime> PO_Comments_Sent_On { get; set; }
        public string Finalized_By { get; set; }
        public Nullable<System.DateTime> Finalized_On { get; set; }
        public string Modification_Reqd_By { get; set; }
        public Nullable<System.DateTime> Modification_Reqd_On { get; set; }
        public string Planner_Confirmed_By { get; set; }
        public Nullable<System.DateTime> Planner_Confirmed_On { get; set; }
        public string Sign_Request_Needed { get; set; }
    }
}
